# Generated by Django 3.0.5 on 2020-10-08 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='ユーザー名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('first_name', models.CharField(max_length=255, verbose_name='名前')),
                ('last_name', models.CharField(max_length=255, verbose_name='苗字')),
                ('profile_image', models.ImageField(upload_to='profile_images/', verbose_name='プロフィール画像')),
                ('tell', models.CharField(max_length=255, verbose_name='電話番号')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='ニックネーム')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='大学名')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='誕生日')),
                ('phone_number', models.CharField(blank=True, max_length=255, verbose_name='携帯電話番号')),
                ('sex', models.CharField(blank=True, choices=[('man', '男性'), ('woman', '女性'), ('others', 'その他'), ('all', '指定なし')], default='', max_length=255, verbose_name='性別')),
                ('year', models.IntegerField(blank=True, choices=[(2022, '2022年卒業'), (2023, '2023年卒業'), (2024, '2024年卒業'), ('all', '指定なし')], null=True, verbose_name='卒年')),
                ('s_and_h', models.CharField(blank=True, choices=[('science', '理系'), ('humanities', '文系'), ('others', 'その他'), ('all', '指定なし')], default='', max_length=255, verbose_name='理文')),
                ('major', models.CharField(blank=True, choices=[('law', '法学部'), ('economics', '経済学部'), ('psychology', '心理学部'), ('engineering', '工学部'), ('sciences', '理学部'), ('all', '指定なし')], default='', max_length=255, verbose_name='専攻')),
                ('indestry1', models.CharField(blank=True, choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], max_length=255, verbose_name='志望業種１')),
                ('indestry2', models.CharField(blank=True, choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], max_length=255, verbose_name='志望業種２')),
                ('indestry3', models.CharField(blank=True, choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], max_length=255, verbose_name='志望業種３')),
                ('job1', models.CharField(blank=True, choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], max_length=255, verbose_name='志望職種１')),
                ('job2', models.CharField(blank=True, choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], max_length=255, verbose_name='志望職種２')),
                ('job3', models.CharField(blank=True, choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], max_length=255, verbose_name='志望職種３')),
                ('company_type', models.CharField(blank=True, choices=[('large_company', '大企業'), ('small_and_medium_company', '中小企業'), ('mega_venture_company', 'メガベンチャー'), ('venture_company', 'ベンチャー'), ('all', '指定なし')], default='', max_length=255, verbose_name='会社規模')),
                ('recruiter_type', models.CharField(blank=True, choices=[('student', '就活生'), ('salon', 'サロン運営者'), ('career_advisor', 'キャリアアドバイザー'), ('corporation', '法人'), ('other', 'その他')], max_length=255, verbose_name='組織タイプ')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='会社名・組織名')),
                ('department_name', models.CharField(blank=True, max_length=255, verbose_name='部署名')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='役職')),
                ('operating_medium', models.CharField(blank=True, max_length=255, verbose_name='運営媒体・運営会社')),
                ('is_student', models.BooleanField(default=False, verbose_name='学生であるか')),
                ('enable_host_event', models.BooleanField(default=False, verbose_name='イベント開催できるか')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('url_height', models.IntegerField(default=100, editable=False, null=True)),
                ('url_width', models.IntegerField(default=100, editable=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True, verbose_name='イベントID')),
                ('name', models.CharField(max_length=255, verbose_name='イベント名')),
                ('host', models.CharField(max_length=255, verbose_name='主催者')),
                ('thumbnail', models.ImageField(height_field='url_height', upload_to='thumbnails/', verbose_name='サムネイル', width_field='url_width')),
                ('place', models.CharField(max_length=255, verbose_name='開催場所')),
                ('event_type_tag', models.CharField(choices=[('group_discussion', 'グループディスカッション'), ('interview', 'インタビュー'), ('information_exchange_meeting', '情報交換会'), ('other', 'その他')], max_length=255, verbose_name='イベントタイプ')),
                ('video_url', models.URLField(blank=True, max_length=3000, null=True, verbose_name='イベントリンク')),
                ('date', models.DateTimeField(verbose_name='開始日時')),
                ('time', models.DurationField(max_length=255, verbose_name='開催時間')),
                ('participant_num', models.PositiveIntegerField(default=0, verbose_name='参加可能人数')),
                ('comment01', models.TextField(verbose_name='当日の流れ')),
                ('comment02', models.TextField(verbose_name='主催者から一言')),
                ('created_by', models.CharField(blank=True, max_length=255, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('enable_matching', models.BooleanField(default=False, verbose_name='全員に表示させる')),
                ('min_matching_score', models.IntegerField(null=True, verbose_name='最低マッチングスコア')),
                ('recommend_users', models.TextField(blank=True, verbose_name='マッチングしたユーザー')),
                ('recommend_users_num', models.PositiveIntegerField(default=5, verbose_name='マッチングさせるユーザーの数')),
                ('sex', models.CharField(choices=[('man', '男性'), ('woman', '女性'), ('others', 'その他'), ('all', '指定なし')], default='', max_length=255, verbose_name='性別')),
                ('year', models.IntegerField(choices=[(2022, '2022年卒業'), (2023, '2023年卒業'), (2024, '2024年卒業'), ('all', '指定なし')], verbose_name='卒年')),
                ('s_and_h', models.CharField(choices=[('science', '理系'), ('humanities', '文系'), ('others', 'その他'), ('all', '指定なし')], default='', max_length=255, verbose_name='理文')),
                ('major', models.CharField(choices=[('law', '法学部'), ('economics', '経済学部'), ('psychology', '心理学部'), ('engineering', '工学部'), ('sciences', '理学部'), ('all', '指定なし')], default='', max_length=255, verbose_name='専攻')),
                ('indestry1', models.CharField(choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], default='', max_length=255, verbose_name='志望業種１')),
                ('indestry2', models.CharField(choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], default='', max_length=255, verbose_name='志望業種２')),
                ('indestry3', models.CharField(choices=[('marketing', 'マーケティング'), ('construction', '建設業'), ('energy', 'エネルギー'), ('chemicals', '化学'), ('media', 'マスコミ'), ('all', '指定なし')], default='', max_length=255, verbose_name='志望業種３')),
                ('job1', models.CharField(choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員'), ('all', '指定なし')], default='', max_length=255, verbose_name='志望職種１')),
                ('job2', models.CharField(choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員'), ('all', '指定なし')], default='', max_length=255, verbose_name='志望職種２')),
                ('job3', models.CharField(choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員'), ('all', '指定なし')], default='', max_length=255, verbose_name='志望職種３')),
                ('company_type', models.CharField(choices=[('large_company', '大企業'), ('small_and_medium_company', '中小企業'), ('mega_venture_company', 'メガベンチャー'), ('venture_company', 'ベンチャー'), ('all', '指定なし')], default='', max_length=255, verbose_name='会社規模')),
                ('url_height', models.IntegerField(editable=False, null=True)),
                ('url_width', models.IntegerField(editable=False, null=True)),
                ('students', models.ManyToManyField(related_name='join_event', to=settings.AUTH_USER_MODEL, verbose_name='参加予定のユーザー')),
            ],
        ),
    ]
