# Generated by Django 3.0.5 on 2020-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='event',
            name='url_width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url_height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='url_width',
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/', verbose_name='サムネイル'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job1',
            field=models.CharField(blank=True, choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員'), ('all', '指定なし')], max_length=255, verbose_name='志望職種１'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job2',
            field=models.CharField(blank=True, choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員'), ('all', '指定なし')], max_length=255, verbose_name='志望職種２'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job3',
            field=models.CharField(blank=True, choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員'), ('all', '指定なし')], max_length=255, verbose_name='志望職種３'),
        ),
    ]
