# Generated by Django 3.0.5 on 2020-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20201008_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='job3',
        ),
        migrations.RemoveField(
            model_name='event',
            name='major',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tell',
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.CharField(max_length=255, verbose_name='卒年'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, choices=[('large_company', '大企業'), ('small_and_medium_company', '中小企業'), ('mega_venture_company', 'メガベンチャー'), ('venture_company', 'ベンチャー')], default='', max_length=255, verbose_name='会社規模'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job1',
            field=models.CharField(blank=True, choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員')], max_length=255, verbose_name='志望職種１'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job2',
            field=models.CharField(blank=True, choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員')], max_length=255, verbose_name='志望職種２'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job3',
            field=models.CharField(blank=True, choices=[('manager', '経営者'), ('engineer', 'エンジニア'), ('personnel', '人事'), ('secretary', '秘書'), ('clerk', '店員')], max_length=255, verbose_name='志望職種３'),
        ),
        migrations.AlterField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, choices=[('law', '法学部'), ('economics', '経済学部'), ('psychology', '心理学部'), ('engineering', '工学部'), ('sciences', '理学部')], default='', max_length=255, verbose_name='専攻'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('man', '男性'), ('woman', '女性'), ('others', 'その他')], default='', max_length=255, verbose_name='性別'),
        ),
    ]
